apiVersion: v1
kind: ConfigMap
metadata:
  name: analytics-config
  namespace: toggle-master
data:
  PORT: "8005"
  AWS_REGION: "us-east-1"
  AWS_SQS_URL: "https://sqs.us-east-1.amazonaws.com/681447159486/togglemaster-dev-evaluation-events"
  AWS_DYNAMODB_TABLE: "ToggleMasterAnalytics"
