apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: targeting-secret
  namespace: toggle-master
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: targeting-secret
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: togglemaster/dev/togglemaster-dev-targeting-db
        property: DATABASE_URL
