apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: flag-secret
  namespace: toggle-master
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: flag-secret
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: togglemaster/dev/togglemaster-dev-flag-db
        property: DATABASE_URL
